name: Subsembly CLI tests

on:
  push:
    paths:
      - "cli/**"

defaults:
  run:
    shell: zsh
    working-directory: cli
jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CLI dependencies
      run: npm install
    - name: Build and link CLI
      run: npm run build && sudo npm link
    - name: Run tests
      run: npm run test