name: Subsembly CLI tests

on:
  push:
    paths:
      - "cli/**"

defaults:
  run:
    working-directory: cli
jobs:
  runtime:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.4'
    - name: Install CLI dependencies
      run: npm install
    - name: Build and link CLI
      run: npm run build && sudo npm link
    - name: Run tests
      run: npm run test