name: Subsembly CLI tests

on: [push]

defaults:
  run:
    working-directory: cli
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '13'
    - name: Install CLI dependencies
      run: npm install
    - name: Build and link CLI
      run: npm run build && sudo npm link
    - name: Run tests
      run: npm run test