name: Compile Runtime

on: [push]
jobs:
    compile-run-node:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install jq and curl
          run: sudo apt-get update && sudo apt-get install jq curl
        - name: Cache node modules
          uses: actions/cache@v2
          env:
            cache-name: cache-node-modules
          with:
            path: |
              '**/node_modules'
              '**/metadata/node_modules'
            key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Use Node.js
          uses: actions/setup-node@v1
          with: 
            node-version: '12.x'
        - name: Install AS dependencies and metadata dependencies
          run: yarn install && cd ./metadata && yarn install
        - name: Compile and run the node in a detached mode
          run: make run-node test=2
        - name: Insert aura keys
          run: bash scripts/insert-aura.sh
        - name: Send transaction
          id: submit-tx
          run: bash scripts/submit-tx.sh 
        - name: Check extrinsic submission
          env: 
            TX_RESULT: ${{steps.submit-tx.outputs.*}}
          run: |
            if [[ $TX_RESULT == *"error" | $TX_RESULT == "1001" ]]; then \
              exit 1; \
            else \
              exit 0; \
            fi \
