name: Smoke Tests

on: [push]
jobs:
    compile-run-node:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install jq and curl
          run: sudo apt-get update && sudo apt-get install jq curl
        - name: Cache node modules
          uses: actions/cache@v2
          env:
            cache-name: cache-node-modules
          with:
            path: |
              '**/node_modules'
              '**/metadata/node_modules'
            key: ${{ runner.os }}-modules-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
        - name: Use Node.js
          uses: actions/setup-node@v1
          with: 
            node-version: '14.4.x'
        - name: Install AS dependencies and metadata dependencies
          run: yarn install && cd ./utils && yarn install
        - name: Compile and run the node in a detached mode
          run: make run-node detached=1
        - name: Insert aura keys
          run: bash scripts/insert-aura.sh
        - name: Sleep for 10 seconds
          uses: jakejarvis/wait-action@master
          with:
            time: '10s'
        - name: Get latest header
          id: check-header
          run: |
            echo "::set-output name=tx-output::$(bash scripts/test-node.sh)\n" 
        - name: |
            Check the latest header
            If it contains number":"0x0",
            it means no block was produced except the genesis
          env: 
            TX_RESULT: ${{steps.check-header.outputs.tx-output}}
          run: |
            if [[ $TX_RESULT == *"number":"0x0"* ]]; then \
              exit 1; \
            else \
              exit 0; \
            fi \
